[theme]
primaryColor = "#E5E5E5"
backgroundColor = "#1e1f23"
secondaryBackgroundColor = "#26282c"
textColor = "#E5E5E5"
font = "monospace"  # Space Mono יפול לקטגוריה הזו

[server]
runOnSave = false
port = 8501
headless = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[client]
showSidebarNavigation = false