[theme]
primaryColor = "#8B5CF6"
backgroundColor = "#0A0A0A"
secondaryBackgroundColor = "#171717"
textColor = "#E5E5E5"
font = "monospace"  # Space Mono יפול לקטגוריה הזו

[server]
runOnSave = false
port = 8501
headless = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[client]
showSidebarNavigation = false